app/urls.py
from django.urls import path
from .views import UrlListView , UrlCreateView, redirect_view, detail 

app_name='app'

urlpatterns = [
    path('list/', UrlListView.as_view()),
    path('create/', UrlCreateView.as_view()),
    path('<str:code>/', redirect_view),
    path('', detail, name='main' )
]

main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include ('app.urls'))
]

app/models.py
from dis import show_code
from django.db import models
from .utils import random_string_generator

# Create your models here.

class Url(models.Model):
    origin_url = models.URLField(unique=True)
    short_code = models.CharField(max_length=6)

    def save(self, *args, **kwargs):
        if not self.short_code:
            self.short_code=random_string_generator(6)
        super(Url, self).save(*args, **kwargs)

    def __str__(self):
        return self.short_code
                  

app/forms.py
from django import forms
from .models import Url

class UrlForm(forms.ModelForm):
    class Meta:
        model=Url
        fields=("origin_url",)
        

app/views.py
from operator import ge
from django.shortcuts import render, redirect
from .serializers import UrlSerializer, UrlCreateSerializer
from .models import Url
from rest_framework import generics
from django.shortcuts import get_object_or_404
from .forms import UrlForm
from django.conf import settings


class UrlListView(generics.ListAPIView):
    queryset = Url.objects.all()
    serializer_class = UrlSerializer


class UrlCreateView(generics.CreateAPIView):
    queryset = Url.objects.all()
    serializer_class = UrlCreateSerializer
    

def redirect_view(request, code):
    url = get_object_or_404(Url, short_code = code)
    return redirect(url.origin_url)


def detail(request):
    search = request.GET.get('q')
    form = UrlForm(request.POST or None)
    urls = Url.objects.all()
    if search:
        urls = urls.filter(origin_url__icontains=search)
    if request.method == "POST" and form.is_valid():
        form.save()

    return render(request, 'index.html', {'form': form, 'urls': urls, 'site_url': settings.SITE_URL })
    

app/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" method= "get" >
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                  <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </header>
<div class= "container" style="width: 500px;">
    <form method="post" action="{% url 'app:main' %}" >
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
<div class="container" style="height: 100px;">
    {% for url in urls %}
    <div class="alert alert-dark" role="alert">
        {{url.origin_url}} <br>
        <a href="{{site_url}}{{url.short_code}}">
          {{site_url}}{{url.short_code}}
        </a>
    </div>
    {% endfor %}
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  
  </body>
</html>